name: decoupled-drupal-react
recipe: drupal9
config:
  via: nginx
  webroot: backend/web
  php: '8.1'
  xdebug: true
services:
  appserver:
    overrides:
      environment:
        PHP_IDE_CONFIG: 'serverName=appserver'
    config:
      php: php.ini
  node:
    type: node:16
    overrides:
      ports:
        - 3000:3000
    globals:
      gulp-cli: latest
tooling:
  drush:
    service: appserver
    cmd: /app/backend/vendor/bin/drush --root=/app/backend/web
  drupal:
    service: appserver
    cmd: /app/backend/vendor/bin/drupal --root=/app/backend/web
  node:
    service: node
  npm:
    service: node
  npx:
    service: node
  yarn:
    service: node
  gulp:
    service: node
