parameters:
  cors.config:
    enabled: true
    # Specify allowed headers, like 'x-allowed-header'.
    allowedHeaders: ['*']
    # Specify allowed request methods, specify ['*'] to allow all possible ones.
    allowedMethods: ['*']
    # Configure requests allowed from specific origins.
    allowedOrigins: ['*']
    # Sets the Access-Control-Expose-Headers header.
    exposedHeaders: ['*']
    # Sets the Access-Control-Max-Age header (20 days)
    maxAge: 1728000
    # Sets the Access-Control-Allow-Credentials header.
    supportsCredentials: true
